config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  resources :transcriptions

  root 'transcriptions#index'
  root 'pages#credit'

end

app/models/transcription.rb
class Transcription < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  def credits
  end
end

app/controllers/transcriptions_controller.rb
class TranscriptionsController < ApplicationController
  before_action :set_transcription, only: [:show, :edit, :update, :destroy]

  # GET /transcriptions
  # GET /transcriptions.json
  def index
    @transcriptions = Transcription.all
  end

  # GET /transcriptions/1
  # GET /transcriptions/1.json
  def show
  end

  # GET /transcriptions/new
  def new
    @transcription = Transcription.new
  end

  # GET /transcriptions/1/edit
  def edit
  end

  # POST /transcriptions
  # POST /transcriptions.json
  def create
    @transcription = Transcription.new(transcription_params)

    respond_to do |format|
      if @transcription.save
        format.html { redirect_to @transcription, notice: 'Transcription was successfully created.' }
        format.json { render :show, status: :created, location: @transcription }
      else
        format.html { render :new }
        format.json { render json: @transcription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transcriptions/1
  # PATCH/PUT /transcriptions/1.json
  def update
    respond_to do |format|
      if @transcription.update(transcription_params)
        format.html { redirect_to @transcription, notice: 'Transcription was successfully updated.' }
        format.json { render :show, status: :ok, location: @transcription }
      else
        format.html { render :edit }
        format.json { render json: @transcription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transcriptions/1
  # DELETE /transcriptions/1.json
  def destroy
    @transcription.destroy
    respond_to do |format|
      format.html { redirect_to transcriptions_url, notice: 'Transcription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transcription
      @transcription = Transcription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transcription_params
      params.require(:transcription).permit(:title, :user_name, :picture, :description, :transcription)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transcriptions_helper.rb
module TranscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scriba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Scriba", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "Transcriptions", transcriptions_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
<%= yield %>
</div>
<footer>
  <div class="container">
    HILT <%= Time.now.year %>
  </div>
</footer>
<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/pages/credit.html.erb
<h1>Credits</h1>
<p>This application was created by me, for this thing I did.</p>
<p>Some other people helped too.</p>

app/views/transcriptions/_form.html.erb
<%= form_for(@transcription, :html => {:multipart => true}) do |f| %>
  <% if @transcription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transcription.errors.count, "error") %> prohibited this transcription from being saved:</h2>

      <ul>
      <% @transcription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :transcription %><br>
    <%= f.text_area :transcription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transcriptions/edit.html.erb
<h1>Editing Transcription</h1>

<%= render 'form' %>

<%= link_to 'Show', @transcription %> |
<%= link_to 'Back', transcriptions_path %>

app/views/transcriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transcriptions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User name</th>
      <th>Picture</th>
      <th>Description</th>
      <th>Transcription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transcriptions.each do |transcription| %>
      <tr>
        <td><%= transcription.title %></td>
        <td><%= transcription.user_name %></td>
        <td><%= transcription.picture %></td>
        <td><%= transcription.description %></td>
        <td><%= image_tag transcription.picture_url(:thumb) if transcription.picture.present? %></td>
        <td><%= transcription.transcription %></td>
        <td><%= link_to 'Show', transcription %></td>
        <td><%= link_to 'Edit', edit_transcription_path(transcription) %></td>
        <td><%= link_to 'Destroy', transcription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transcription', new_transcription_path %>

app/views/transcriptions/new.html.erb
<h1>New Transcription</h1>

<%= render 'form' %>

<%= link_to 'Back', transcriptions_path %>

app/views/transcriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @transcription.title %>
</p>

<p>
  <strong>User name:</strong>
  <%= @transcription.user_name %>
</p>

<p>
  <strong>Picture:</strong><p>
  <%= image_tag(@transcription.picture_url, :width => 600) if @transcription.picture.present? %></p>
</p>


<p>
  <strong>Description:</strong>
  <%= @transcription.description %>
</p>

<p>
  <strong>Transcription:</strong>
  <%= @transcription.transcription %>
</p>



<%= link_to 'Edit', edit_transcription_path(@transcription) %> |
<%= link_to 'Back', transcriptions_path %>